export const ROUTES = {
  HOME: "/",
  GENDEAR_REVEAL: "gender-reveal",
  ABOUT: "about",
  IDEAL_WEIGHT: "ideal-weight",
  API_NATIONALAZE: "products",
  APP_ROUTE: "app-route",
  USERS: "users",
  PROFILE: "/profile",
  SETTINGS: "settings",
  NOT_FOUND: "*",
  PRODUCT: (id: string | number) => `/products/${id}`,
  SIGN_UP: "/signup",
  SIGN_IN: "/signin",
  CREATE_CATEGORY: "categories/add",
  COUNTER: "counter",
  FEATURED_PRODUCTS: "/products",
  PRODUCTS: "products",
} as const;
